name: VoidVaults
version: 1.1.0
main: com.voidvault.VoidVaultPlugin
api-version: '1.17'
author: VoidVault Team
description: Modern, performance-first Ender Chest replacement
website: https://example.com

softdepend: [Vault, PlaceholderAPI]

commands:
  voidvaults:
    description: VoidVaults admin commands
    usage: /voidvaults <open|reload|setslots|setpages>
    aliases: [vvs, vv]
  echest:
    description: Open your vault remotely
    usage: /echest
    aliases: [pv, vault]

permissions:
  voidvaults.slots.9:
    description: Access to 9 slots
    default: false
  voidvaults.slots.18:
    description: Access to 18 slots
    default: false
  voidvaults.slots.27:
    description: Access to 27 slots
    default: false
  voidvaults.slots.36:
    description: Access to 36 slots
    default: false
  voidvaults.slots.45:
    description: Access to 45 slots
    default: false
  voidvaults.slots.54:
    description: Access to 54 slots
    default: false
  voidvaults.slots.52:
    description: Access to 52 slots (PAGED mode max)
    default: false
  
  voidvaults.page.1:
    description: Access to page 1
    default: true
  voidvaults.page.2:
    description: Access to page 2
    default: false
  voidvaults.page.3:
    description: Access to page 3
    default: false
  voidvaults.page.4:
    description: Access to page 4
    default: false
  voidvaults.page.5:
    description: Access to page 5 (maximum)
    default: false
  
  voidvaults.remote:
    description: Use remote access command
    default: op
  voidvaults.remote.bypasscooldown:
    description: Bypass remote access cooldown
    default: op
  
  voidvaults.admin.openother:
    description: Open other players' vaults
    default: op
  voidvaults.admin.reload:
    description: Reload configuration
    default: op
  voidvaults.admin.setslots:
    description: Override slot permissions
    default: op
  voidvaults.admin.setpages:
    description: Override page permissions
    default: op
